/** Telangana Feast Editorial: the brand story uses crafted, quiet confidence rather than generic hospitality claims. */
import { Check, ShieldCheck, UsersRound } from "lucide-react";
import { PageShell } from "@/components/SiteChrome";
import { Seo } from "@/components/Seo";

const photo = "/manus-storage/dhruva-copper-buffet_52259e59.jpeg";

export default function About() {
  return <PageShell><Seo title="About Dhruva Catering Services | Hanamkonda" description="Learn about Dhruva Catering Services, serving thoughtful Telangana, South Indian and North Indian menus for events across Hanamkonda and beyond." /><main>
    <section className="bg-[#621111] px-5 py-20 text-[#FFF9EF] sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-[1440px]"><p className="flex items-center gap-3 text-[0.66rem] font-bold uppercase tracking-[0.2em] text-[#FFD27A]"><span className="h-px w-9 bg-[#D4AF37]" />Our story</p><h1 className="mt-6 max-w-4xl font-display text-[clamp(3.4rem,7vw,7.1rem)] font-semibold leading-[0.9] tracking-[-0.07em]">The best celebrations have a certain <span className="italic text-[#FFC16B]">ease</span> to them.</h1></div></section>
    <section className="bg-[#FFF9EF] py-20 sm:py-28"><div className="mx-auto grid max-w-[1440px] gap-14 px-5 sm:px-8 lg:grid-cols-[0.95fr_1.05fr] lg:gap-20 lg:px-10"><div className="relative min-h-[390px] overflow-hidden rounded-[2.2rem_0.5rem_2.2rem_0.5rem] bg-[#F3E0BF]"><img src={photo} alt="An abundant Indian catering buffet with copper servingware" className="absolute inset-0 h-full w-full object-cover" loading="lazy" /></div><div className="flex flex-col justify-center"><p className="text-[0.66rem] font-bold uppercase tracking-[0.2em] text-[#9A5C0E]">Built around the host</p><h2 className="mt-5 font-display text-5xl font-semibold leading-[0.97] tracking-[-0.055em] text-[#621111]">Care in the kitchen. Calm in the room.</h2><p className="mt-6 font-body text-base leading-7 text-[#714D40]">Dhruva Catering Services brings traditional Indian flavours to events of every scale with a simple promise: good food should arrive with thoughtful timing, clean preparation, and a team that understands the flow of a celebration.</p><p className="mt-5 font-body text-base leading-7 text-[#714D40]">Our menus draw from Telangana, South Indian, and North Indian culinary traditions, then flex around your guests, venue, family preferences, and occasion.</p></div></div></section>
    <section className="bg-[#F6E9D5] py-20 sm:py-24"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-10"><div className="grid gap-8 md:grid-cols-3"><article className="border-t-2 border-[#D4AF37] pt-6"><ShieldCheck className="size-7 text-[#F28C28]" /><h3 className="mt-8 font-display text-3xl font-semibold tracking-[-0.04em] text-[#621111]">Hygiene-led preparation</h3><p className="mt-3 font-body text-sm leading-6 text-[#714D40]">Careful food handling and a clean working process are fundamental to every menu we serve.</p></article><article className="border-t-2 border-[#D4AF37] pt-6"><UsersRound className="size-7 text-[#F28C28]" /><h3 className="mt-8 font-display text-3xl font-semibold tracking-[-0.04em] text-[#621111]">Trained service teams</h3><p className="mt-3 font-body text-sm leading-6 text-[#714D40]">Our on-ground team helps the meal service feel warm, organised, and guest-ready.</p></article><article className="border-t-2 border-[#D4AF37] pt-6"><Check className="size-7 text-[#F28C28]" /><h3 className="mt-8 font-display text-3xl font-semibold tracking-[-0.04em] text-[#621111]">Menus with intention</h3><p className="mt-3 font-body text-sm leading-6 text-[#714D40]">A meaningful spread respects regional flavour, personal preference, and the practical rhythm of the day.</p></article></div></div></section>
  </main></PageShell>;
}
