/** Telangana Feast Editorial: an interactive culinary menu is anchored by a substantial feast window and ceremonial course divisions. */
import { Download, MessageCircle } from "lucide-react";
import { useState } from "react";
import { BUSINESS, PageShell } from "@/components/SiteChrome";
import { Seo } from "@/components/Seo";
import { ASSETS } from "@/lib/assets";

const menuPdf = ASSETS.sampleMenu;
const menuImage = ASSETS.menuSpread;
const menus = [
  { id: "veg", label: "Traditional Veg Feast", lead: "A soulful vegetarian spread built around fresh regional flavours and thoughtful combinations.", groups: [{ title: "A welcome start", items: ["Welcome drink selection", "Seasonal savoury bites", "Traditional snack course"] }, { title: "Main feast", items: ["Regional curries & dals", "Fresh breads and rice preparations", "Curd rice and accompaniments"] }, { title: "Finishing notes", items: ["Traditional sweet course", "Seasonal fruit", "Pan or digestive option"] }] },
  { id: "nonveg", label: "Non-Veg Specialties", lead: "A celebratory non-vegetarian menu shaped around comforting favourites and memorable centrepieces.", groups: [{ title: "Signature starters", items: ["Chef-selected chicken starter", "Regional non-vegetarian appetiser", "Fresh vegetarian companion starter"] }, { title: "Main table", items: ["Chicken or mutton speciality", "Seasonal curry selection", "Rice, breads & accompaniments"] }, { title: "Sweet conclusion", items: ["Indian dessert selection", "Ice cream or chilled dessert", "Seasonal fruit"] }] },
  { id: "starters", label: "Starters & Biryanis", lead: "Live energy and crowd-pleasing dishes for a vibrant celebration spread.", groups: [{ title: "Live & crisp", items: ["Live dosa / regional counter", "Vegetarian starter selection", "Non-vegetarian starter selection"] }, { title: "Biryani table", items: ["Vegetarian biryani", "Chicken or mutton biryani", "Raita, mirchi ka salan & accompaniments"] }, { title: "Add-ons", items: ["Chaat counter", "Tea and coffee service", "Fresh fruit counter"] }] },
  { id: "sweet", label: "Sweets & Desserts", lead: "A final course that feels festive, generous, and beautifully arranged.", groups: [{ title: "Indian classics", items: ["Gulab jamun", "Rasmalai or milk sweet", "Regional mithai selection"] }, { title: "Chilled treats", items: ["Ice cream station", "Fruit-based dessert", "Dessert cup selection"] }, { title: "Custom finish", items: ["Celebration cake coordination", "Premium sweet additions", "Return-gift sweet packs by request"] }] },
];

export default function Menu() {
  const [active, setActive] = useState(menus[0].id);
  const selected = menus.find((menu) => menu.id === active) ?? menus[0];
  return <PageShell><Seo title="Catering Menu | Dhruva Catering Services" description="Explore sample traditional vegetarian, non-vegetarian, biryani, starters and dessert menus from Dhruva Catering Services in Hanamkonda." /><main>
    <section className="bg-[#621111] px-5 py-20 text-[#FFF9EF] sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-[1440px]"><p className="flex items-center gap-3 text-[0.66rem] font-bold uppercase tracking-[0.2em] text-[#FFD27A]"><span className="h-px w-9 bg-[#D4AF37]" />A starting point</p><h1 className="mt-6 max-w-4xl font-display text-[clamp(3.4rem,6.8vw,7rem)] font-semibold leading-[0.9] tracking-[-0.07em]">Menus with room for your <span className="italic text-[#FFC16B]">occasion.</span></h1><p className="mt-7 max-w-xl font-body text-lg leading-8 text-[#F9E7D0]/80">Browse a selection of possible menu directions. Your final menu is planned around guest count, event format, preferences, and the season.</p></div></section>
    <section className="bg-[#F6E9D5] px-5 py-12 sm:px-8 lg:px-10"><div className="mx-auto grid max-w-[1160px] gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-center"><figure className="scallop-shell max-w-[360px] shadow-[12px_14px_0_#D4AF37]"><img src={menuImage} alt="Indian dishes arranged as an abundant celebratory feast" className="h-[270px] w-full object-cover" loading="lazy" /><figcaption className="absolute bottom-6 left-6 rounded-full bg-[#621111] px-4 py-2 text-[0.6rem] font-bold uppercase tracking-[0.16em] text-white">A hosted spread</figcaption></figure><div><p className="text-[0.66rem] font-bold uppercase tracking-[0.2em] text-[#9A5C0E]">A menu is more than a list</p><p className="mt-4 max-w-xl font-display text-4xl font-semibold leading-[1] tracking-[-0.045em] text-[#621111]">Regional depth, generous courses, and a proper finish.</p><p className="mt-4 max-w-xl font-body text-sm leading-6 text-[#714D40]">Use the menu sampler to find the right direction, then let us shape the selections around your event.</p></div></div></section>
    <section className="bg-[#FFF9EF] py-16 sm:py-20"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-6 border-b border-[#800000]/15 pb-8 lg:flex-row lg:items-end"><div role="tablist" aria-label="Menu categories" className="flex max-w-full gap-2 overflow-x-auto pb-2"><div className="flex min-w-max gap-2">{menus.map((menu) => <button type="button" key={menu.id} role="tab" aria-selected={active === menu.id} onClick={() => setActive(menu.id)} className={`min-h-11 rounded-full px-4 text-[0.69rem] font-bold uppercase tracking-[0.09em] transition-colors ${active === menu.id ? "bg-[#800000] text-white" : "border border-[#800000]/20 text-[#621111] hover:bg-[#F6E9D5]"}`}>{menu.label}</button>)}</div></div><a href={menuPdf} download className="inline-flex min-h-11 shrink-0 items-center gap-2 text-[0.7rem] font-bold uppercase tracking-[0.1em] text-[#800000] hover:text-[#F28C28]"><Download className="size-4" /> Download sample menu</a></div>
      <div role="tabpanel" className="mt-12 grid gap-12 lg:grid-cols-[0.72fr_1.28fr] lg:gap-20"><div><p className="text-[0.66rem] font-bold uppercase tracking-[0.2em] text-[#9A5C0E]">{selected.label}</p><h2 className="mt-5 font-display text-5xl font-semibold leading-[0.97] tracking-[-0.055em] text-[#621111]">Designed as a generous, well-paced table.</h2><p className="mt-6 font-body text-base leading-7 text-[#714D40]">{selected.lead}</p><a href={BUSINESS.whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#F28C28] px-6 text-[0.72rem] font-bold uppercase tracking-[0.1em] text-[#451207] hover:-translate-y-0.5 hover:bg-[#FFB35F] active:scale-[0.97]"><MessageCircle className="size-4" /> Customise this menu</a></div><div className="grid gap-5 md:grid-cols-3">{selected.groups.map((group, index) => <article key={group.title} className="rounded-[42%_42%_1.4rem_1.4rem/13%_13%_1.4rem_1.4rem] border border-[#800000]/12 bg-[#F6E9D5] p-6"><p className="font-display text-2xl italic text-[#D4AF37]">0{index + 1}</p><h3 className="mt-8 font-display text-2xl font-semibold tracking-[-0.035em] text-[#621111]">{group.title}</h3><ul className="mt-5 grid gap-4 font-body text-sm leading-6 text-[#714D40]">{group.items.map((item) => <li key={item} className="border-t border-[#800000]/10 pt-3">{item}</li>)}</ul></article>)}</div></div>
    </div></section><section className="bg-[#F6E9D5] px-5 py-14 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1440px]"><p className="max-w-3xl font-display text-3xl font-semibold leading-[1.08] tracking-[-0.04em] text-[#621111]">All items are indicative and can be tailored. Ask us about regional specialities, Jain-friendly preparation, children’s menus, and live counters.</p></div></section>
  </main></PageShell>;
}
