/** Telangana Feast Editorial: distinct catering occasions intersect with platter-shaped food imagery and an asymmetric service index. */
import { ArrowRight, Building2, CakeSlice, Flame, HeartHandshake } from "lucide-react";
import { Link } from "wouter";
import { PageShell } from "@/components/SiteChrome";
import { Seo } from "@/components/Seo";
import { ScrollReveal } from "@/components/ScrollReveal";

const serviceImage = "/manus-storage/dhruva-service-table-optimized_4368da80.webp";
const serviceList = [
  { icon: HeartHandshake, number: "01", title: "Wedding & reception banquets", image: "/manus-storage/dhruva-wedding-table-fast_104d449f.webp", alt: "An Indian wedding celebration table with catering service", caption: "Wedding banquets", text: "From the welcome tea to the final sweet course, we build a meal service that matches the scale and sequence of your wedding celebration.", notes: ["Traditional & contemporary menu planning", "Buffet service for large guest lists", "Vegetarian and non-vegetarian formats"] },
  { icon: CakeSlice, number: "02", title: "Birthdays, engagements & private parties", image: "/manus-storage/dhruva-desserts-optimized_f0056a0a.webp", alt: "Indian sweets arranged for a private celebration", caption: "Private celebrations", text: "A personal gathering still deserves a well-made spread. We tailor the menu to your guests and make every serving feel generous.", notes: ["From 50 guests upward", "Family-oriented custom menus", "Flexible meal and snack service"] },
  { icon: Flame, number: "03", title: "Live counter experiences", image: "/manus-storage/dhruva-live-counter-optimized_83ef3cb2.webp", alt: "Chefs serving food from a live catering counter", caption: "Freshly prepared", text: "Bring the theatre of fresh preparation into the celebration with live counters that make the food part of the occasion.", notes: ["Dosa and regional live counters", "Made-to-order guest interaction", "Fresh service at the right pace"] },
  { icon: Building2, number: "04", title: "Corporate catering", image: "/manus-storage/dhruva-menu-spread-optimized_f99233c0.webp", alt: "A large-format Indian food spread ready for a catered event", caption: "Large-format service", text: "Professional meal service for conferences, launches, employee gatherings, and large-format corporate occasions.", notes: ["Structured event coordination", "Small teams to high-volume service", "Menu options across Indian cuisines"] },
];

export default function Services() {
  return <PageShell><Seo title="Catering Services in Hanamkonda | Dhruva Catering" description="Explore Dhruva Catering Services for weddings, receptions, private parties, live counters and corporate catering in Hanamkonda, Warangal and Telangana." /><main>
    <section className="overflow-hidden bg-[#F6E9D5] px-5 py-16 sm:px-8 sm:py-20 lg:px-10"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.06fr_0.94fr] lg:items-end lg:gap-20"><div><p className="text-[0.66rem] font-bold uppercase tracking-[0.2em] text-[#9A5C0E]">The service menu</p><h1 className="mt-6 max-w-3xl font-display text-[clamp(3.4rem,6.5vw,6.8rem)] font-semibold leading-[0.91] tracking-[-0.07em] text-[#621111]">A dining experience that keeps the occasion moving.</h1><p className="mt-7 max-w-xl font-body text-lg leading-8 text-[#714D40]">From 50 guests to 5,000+, Dhruva has a service format for the way you are gathering.</p><div className="mt-9 flex items-center gap-4"><span className="h-px w-16 bg-[#D4AF37]" /><span className="text-[0.64rem] font-bold uppercase tracking-[0.16em] text-[#800000]">Banquets · live counters · teams</span></div></div><figure className="scallop-shell mx-auto w-full max-w-[510px] rotate-[-2deg] shadow-[16px_18px_0_#800000]"><img src={serviceImage} alt="An elegant Indian catering table prepared for guests" className="h-[345px] w-full object-cover" loading="lazy" /><figcaption className="absolute bottom-7 left-7 rounded-full bg-[#800000] px-4 py-2 text-[0.62rem] font-bold uppercase tracking-[0.17em] text-white">Service, in motion</figcaption></figure></div></section>
    <section className="bg-[#FFF9EF] py-6 sm:py-10"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-10"><div className="grid lg:grid-cols-[0.15fr_1fr]"><aside className="hidden border-r border-[#800000]/15 pt-14 lg:block"><p className="-rotate-90 origin-top-left translate-x-[-2.5rem] whitespace-nowrap text-[0.63rem] font-bold uppercase tracking-[0.2em] text-[#9A5C0E]">Choose your occasion</p></aside><div>{serviceList.map((service) => { const Icon = service.icon; return <article key={service.number} className="grid gap-7 border-b border-[#800000]/15 py-12 lg:grid-cols-[0.12fr_0.82fr_1fr_0.68fr] lg:gap-9 lg:py-16"><div className="font-display text-2xl italic text-[#D4AF37]">{service.number}</div><div><Icon className="size-7 text-[#F28C28]" strokeWidth={1.8} /><h2 className="mt-7 font-display text-4xl font-semibold leading-[1] tracking-[-0.045em] text-[#621111]">{service.title}</h2></div><div className="lg:pt-10"><p className="max-w-xl font-body text-base leading-7 text-[#714D40]">{service.text}</p><ul className="mt-6 grid gap-3 text-sm font-medium text-[#5B3125]">{service.notes.map((note) => <li key={note} className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[#F28C28]" />{note}</li>)}</ul></div><ScrollReveal><figure className="scallop-shell h-[190px] self-end shadow-[8px_10px_0_#D4AF37] lg:h-[208px]"><img src={service.image} alt={service.alt} loading="lazy" decoding="async" className="h-full w-full object-cover" /><figcaption className="absolute bottom-4 left-4 rounded-full bg-[#621111]/92 px-3 py-1.5 text-[0.55rem] font-bold uppercase tracking-[0.14em] text-white backdrop-blur">{service.caption}</figcaption></figure></ScrollReveal></article>})}</div></div></div></section>
    <section className="bg-[#800000] px-5 py-16 text-white sm:px-8 lg:px-10"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-7 lg:flex-row lg:items-center"><h2 className="max-w-2xl font-display text-5xl font-semibold leading-[0.96] tracking-[-0.05em]">Need help deciding what fits your event?</h2><Link href="/contact" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-full bg-[#F28C28] px-6 text-[0.72rem] font-bold uppercase tracking-[0.1em] text-[#451207] hover:bg-[#FFB35F] active:scale-[0.97]">Discuss your event <ArrowRight className="size-4" /></Link></div></section>
  </main></PageShell>;
}
